from __future__ import annotations

from datetime import date, timedelta

from apps.events import emit_event, workflow_event
from core.database import now
from core.shared import next_no

from .sla import ensure_work_sla


def create_condition_work_order(
    conn,
    *,
    rule: dict,
    channel: dict,
    event_no: str,
    value: float,
    actor_id: int,
    fmea: dict | None,
    approval_creator,
    condition_text: str,
) -> dict:
    """Create the governed maintenance work order produced by a CBM recommendation."""
    asset_row = conn.execute(
        'SELECT id,asset_no,name,location_id FROM assets WHERE id=?', (channel['asset_id'],)
    ).fetchone()
    if not asset_row:
        raise LookupError('CBM asset not found')
    asset = dict(asset_row)
    wo_no = next_no(conn, 'work_orders', 'wo_no', 'WO-', 10026)
    priority = rule.get('work_priority') or ('Critical' if rule.get('severity') == 'Critical' else 'High')
    finish_days = 1 if priority in ('Emergency', 'Critical') else 2 if priority == 'High' else 5
    title = f"CBM: {rule['name']} — {asset['asset_no']}"
    fmea_text = (
        f" Linked FMEA {fmea['fmea_no']} / {fmea['mode_no']} ({fmea['failure_mode_name']}), "
        f"current RPN {fmea['rpn']} {fmea['risk_band']}."
        if fmea else ''
    )
    description = (
        f"Generated by {rule['rule_no']} after {int(rule['consecutive_readings'])} consecutive Good-quality reading(s). "
        f"Channel {channel['channel_code']} measured {value:g} {channel.get('unit') or ''}; "
        f"rule condition {condition_text}. Source event {event_no}.{fmea_text}"
    )
    instructions = (
        rule.get('instructions')
        or (fmea.get('recommended_action') if fmea else '')
        or 'Inspect the asset condition, validate the signal and perform condition-based maintenance as required.'
    ).strip()
    failure_code = fmea['mode_no'] if fmea else f"CBM-{rule['rule_no']}"
    stamp = now()
    cur = conn.execute(
        '''INSERT INTO work_orders(
             wo_no,title,description,asset_id,location_id,priority,status,work_type,failure_code,asset_fmea_id,
             requested_by,target_start,target_finish,estimated_hours,instructions,created_at,updated_at
           ) VALUES(?,?,?,?,?,?,'Submitted','Condition-Based Maintenance',?,?,?,?,?,?,?,?,?)''',
        (
            wo_no, title, description, asset['id'], asset.get('location_id'), priority, failure_code,
            fmea['id'] if fmea else None, actor_id, date.today().isoformat(),
            (date.today() + timedelta(days=finish_days)).isoformat(), 2.0, instructions, stamp, stamp,
        ),
    )
    ensure_work_sla(conn, cur.lastrowid)
    approval_creator(
        conn, 'Work Management', 'work_order', cur.lastrowid, wo_no,
        f"Approve {wo_no} — {title}", actor_id, assigned_role='maintenance_manager',
    )
    workflow_event(
        conn, 'Work Management', 'work_order', cur.lastrowid, wo_no,
        'CBM GENERATED', '', 'Submitted', actor_id, event_no,
    )
    emit_event(
        conn, 'maintenance.cbm.work_order_created', 'cbm_event', event_no,
        {
            'event_no': event_no,
            'rule_no': rule['rule_no'],
            'work_order': wo_no,
            'asset_id': asset['id'],
            'fmea_no': fmea['fmea_no'] if fmea else None,
        },
    )
    return {'id': cur.lastrowid, 'wo_no': wo_no}
