"""HTML renderers for protected EUAS reports.

All values originating from the database or immutable report snapshots are
escaped before insertion into markup. Structural HTML remains application-owned.
"""
from __future__ import annotations

from html import escape
from typing import Any, Mapping, Sequence


REPORT_STYLESHEET = '/static/report.css'


def _h(value: Any, default: str = '') -> str:
    """Return a value safe for insertion into HTML text/attribute contexts."""
    if value is None:
        value = default
    return escape(str(value), quote=True)


def render_snapshot_report_html(report: Mapping[str, Any], snapshot: Mapping[str, Any]) -> str:
    asset = snapshot['asset']
    works: Sequence[Mapping[str, Any]] = snapshot.get('work_orders') or []
    costs: Sequence[Mapping[str, Any]] = snapshot.get('costs') or []
    total = sum(float(item.get('amount') or 0) for item in costs)
    work_rows = ''.join(
        '<tr>'
        f'<td>{_h(item.get("wo_no"))}</td>'
        f'<td>{_h(item.get("title"))}</td>'
        f'<td>{_h(item.get("status"))}</td>'
        f'<td>{_h(item.get("actual_hours"))}</td>'
        f'<td>{_h(item.get("actual_cost"))}</td>'
        '</tr>'
        for item in works
    )
    return (
        '<html><head>'
        f'<title>{_h(report.get("report_no"))}</title>'
        f'<link rel="stylesheet" href="{REPORT_STYLESHEET}">'
        '</head><body class="report snapshot-report">'
        '<h1>ELSEWEDY UTILITIES</h1>'
        f'<h2>{_h(report.get("title"))}</h2>'
        f'<p><b>Report:</b> {_h(report.get("report_no"))}<br>'
        f'<b>Snapshot:</b> {_h(report.get("generated_at"))}<br>'
        f'<b>SHA-256:</b> {_h(report.get("content_hash"))}</p>'
        '<h3>Asset</h3>'
        f'<p><b>{_h(asset.get("asset_no"))} — {_h(asset.get("name"))}</b><br>'
        f'{_h(asset.get("site_name"))} · {_h(asset.get("location_name"))}<br>'
        f'Condition: {_h(asset.get("condition"))} | Status: {_h(asset.get("status"))} | '
        f'Criticality: {_h(asset.get("criticality"))}</p>'
        '<h3>Maintenance Cost</h3>'
        f'<p><b>{total:.2f}</b></p>'
        '<h3>Work History</h3>'
        '<table><tr><th>WO</th><th>Description</th><th>Status</th><th>Hours</th><th>Cost</th></tr>'
        f'{work_rows}</table>'
        '<small>Immutable EUAS report snapshot — Developed by Omar &amp; Seif</small>'
        '</body></html>'
    )


def render_work_order_report_html(
    work_order: Mapping[str, Any],
    labor: Sequence[Mapping[str, Any]],
    materials: Sequence[Mapping[str, Any]],
) -> str:
    labor_rows = ''.join(
        '<tr>'
        f'<td>{_h(item.get("full_name"))}</td>'
        f'<td>{_h(item.get("hours"))}</td>'
        f'<td>{_h(item.get("notes"))}</td>'
        '</tr>'
        for item in labor
    )
    material_rows = ''.join(
        '<tr>'
        f'<td>{_h(item.get("item_no"))} {_h(item.get("name"))}</td>'
        f'<td>{_h(item.get("quantity"))}</td>'
        f'<td>{_h(item.get("unit_cost"))}</td>'
        '</tr>'
        for item in materials
    )
    actual_cost = float(work_order.get('actual_cost') or 0)
    return (
        '<html><head>'
        f'<title>{_h(work_order.get("wo_no"))}</title>'
        f'<link rel="stylesheet" href="{REPORT_STYLESHEET}">'
        '</head><body class="report work-report">'
        '<h1>ELSEWEDY UTILITIES</h1>'
        f'<h2>{_h(work_order.get("wo_no"))} — {_h(work_order.get("title"))}</h2>'
        f'<p><b>Asset:</b> {_h(work_order.get("asset_no"), "-")} {_h(work_order.get("asset_name"))}<br>'
        f'<b>Status:</b> {_h(work_order.get("status"))} | <b>Priority:</b> {_h(work_order.get("priority"))} | '
        f'<b>Type:</b> {_h(work_order.get("work_type"))}<br>'
        f'<b>Assigned:</b> {_h(work_order.get("assigned_to_name"), "-")} | '
        f'<b>Supervisor:</b> {_h(work_order.get("supervisor_name"), "-")}</p>'
        '<h3>Description</h3>'
        f'<p>{_h(work_order.get("description"))}</p>'
        '<h3>Instructions / Safety</h3>'
        f'<p>{_h(work_order.get("instructions"))}<br>{_h(work_order.get("safety_requirements"))}</p>'
        '<h3>Labor</h3>'
        f'<table><tr><th>Person</th><th>Hours</th><th>Notes</th></tr>{labor_rows}</table>'
        '<h3>Materials</h3>'
        f'<table><tr><th>Item</th><th>Qty</th><th>Unit Cost</th></tr>{material_rows}</table>'
        f'<p><b>Actual Cost:</b> {actual_cost:.2f}</p>'
        '<small>Generated by EUAS — Developed by Omar &amp; Seif</small>'
        '</body></html>'
    )
